export class Caratteristiche {
    constructor(
        public id: number | null,
        public descrizione: string | null,
        public esposizione: string | null,
        public speseCondominiali: number | null,
        public speseExtraNote: string | null,
        public ascensore: boolean | null,
        public arredamento: string | null,
        public balconi: string | null,
        public terrazzi: string | null,
        public box: string | null,
        public giardino: string | null,
        public taverna: string | null,
        public mansarda: string | null,
        public cantina: string | null,
        public speseRiscaldamento: number | null,
        public ariaCondizionata: string | null,
        public proprieta: string | null,
        public categoriaCatastale: string | null,
        public rendita: number | null,
        public impiantoElettrico: string | null,
        public impiantoIdraulico: string | null,
        public livelli: number | null,
        public serramentiInterni: string | null,
        public serramentiEsterni: string | null,
        public portaBlindata: boolean | null,
        public antifurto: string | null,
        public citofono: string | null,
        public annoCostruzione: number | null,
        public portineria: string | null,
        public combustibile: string | null,
        public cablato: string | null,
        public tipoContratto: string | null,
        public cauzione: string | null,
        public reception: string | null,
        public altezza: string | null,
        public totalePiani: number | null
    ) {}
}
