export class Caratteristiche {
    constructor(
        public id: number,
        public descrizione: string,
        public esposizione: string,
        public speseCondominiali: number,
        public speseExtraNote: string,
        public ascensore: boolean,
        public arredamento: string,
        public balconi: string,
        public terrazzi: string,
        public box: string,
        public giardino: string,
        public taverna: string,
        public mansarda: string,
        public cantina: string,
        public speseRiscaldamento: number,
        public ariaCondizionata: string,
        public proprieta: string,
        public categoriaCatastale: string,
        public rendita: number,
        public impiantoElettrico: string,
        public impiantoIdraulico: string,
        public livelli: number,
        public serramentiInterni: string,
        public serramentiEsterni: string,
        public portaBlindata: boolean,
        public antifurto: string,
        public citofono: string,
        public annoCostruzione: number,
        public portineria: string,
        public combustibile: string,
        public cablato: string,
        public tipoContratto: string,
        public cauzione: string,
        public reception: string,
        public altezza: string,
        public totalePiani: number
    ) {}
}
